plugins {
    alias(libs.plugins.android.app) apply false
    alias(libs.plugins.android.lib) apply false
    alias(libs.plugins.kotlin.android) apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }

    configurations.configureEach {
        resolutionStrategy.dependencySubstitution {
            substitute module("org.secuso.pfacore:model") using project(":model")
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}